"""Generate bilingual CLI tables from the actual argparse definitions."""

import argparse
from pathlib import Path

from fermi_softness import __version__
from fermi_softness.cli import parser

ROOT = Path(__file__).resolve().parents[1]
COMMANDS = {
    "compute": ("Reconstruct the smooth PAW field.", "重建 PAW 平滑赝波函数软度场。"),
    "prepare-parchg": ("Prepare a state-resolved native export.", "准备逐态原生密度导出。"),
    "compute-parchg": ("Combine the prepared native state densities.", "合成已准备的逐态原生密度。"),
    "prepare-frozen": ("Prepare compact nonmagnetic export.", "准备非磁体系的紧凑导出。"),
    "compute-frozen": ("Import the checked fixed-orbital density.", "导入通过检查的固定轨道密度。"),
    "inspect": ("Inspect WAVECAR format and FFT dimensions.", "检查 WAVECAR 格式及 FFT 网格。"),
    "gui": ("Open Fermi Softness Studio.", "打开 Fermi Softness Studio。"),
    "demos": ("List the offline demo catalog.", "列出离线示例目录。"),
    "install-app": ("Install the macOS application icon and launcher.", "安装 macOS 应用程序图标和启动入口。"),
    "install-bader": ("Install the pinned official Bader executable.", "安装固定版本的官方 Bader 程序。"),
    "demo": ("Write synthetic teaching data.", "生成合成教学数据。"),
    "render": ("Render a field as PNG or TIFF.", "将数值场绘制为 PNG 或 TIFF。"),
    "animate": ("Export a rotating view as MP4 or GIF.", "将旋转视图导出为 MP4 或 GIF。"),
    "integrate": ("Integrate an existing grid-aligned partition.", "对已经与网格对齐的外部分区积分。"),
    "bader": ("Generate charge-defined basins and integrate softness.", "根据电荷生成 Bader 分区并积分软度。"),
    "select-basins": ("Save a field restricted to selected atoms.", "保存仅包含所选原子区域的软度场。"),
}
OPTIONS = {
    "wavecar": ("Source WAVECAR.", "源 WAVECAR 文件。"),
    "vasprun": ("Matching source vasprun.xml (gzip supported).", "匹配的源 vasprun.xml，支持 gzip。"),
    "kt": ("Descriptor kT in eV; independent of SCF SIGMA.", "描述符 kT，单位 eV；独立于 SCF SIGMA。"),
    "threshold": ("Absolute derivative cutoff, eV^-1.", "费米函数导数的绝对截断阈值，单位 eV⁻¹。"),
    "mu": ("Override Fermi energy, eV; otherwise use source metadata.", "覆盖费米能，单位 eV；省略时使用源元数据。"),
    "grid": ("Three FFT dimensions NX NY NZ; automatic if omitted.", "FFT 三个维度 NX NY NZ；省略时自动选择。"),
    "gamma_half": ("Gamma half-storage axis.", "Gamma 半空间存储方向。"),
    "max_memory_gb": ("Working-memory estimate budget, GB.", "工作内存估算预算，单位 GB。"),
    "allow_incomplete": ("Permit diagnostic output with insufficient bands.", "允许空带不足的诊断输出。"),
    "allow_reduced": ("Permit diagnostic unsymmetrized output.", "允许未经对称性展开的诊断输出。"),
    "incar": ("Source INCAR; if omitted, look beside vasprun.xml.", "源 INCAR；省略时在 vasprun.xml 所在目录查找。"),
    "output": ("Destination file or directory (see workflow below).", "输出文件或目录，见下方说明。"),
    "directory": ("Applications folder; defaults to /Applications if writable, otherwise ~/Applications.", "应用程序目录；默认优先使用可写的 /Applications，否则使用 ~/Applications。"),
    "open_app": ("Open Studio after installing its macOS application entry.", "安装 macOS 应用入口后立即打开 Studio。"),
    "manifest": ("Generated manifest.json; keep it with the export outputs.", "生成的 manifest.json，应与导出结果放在一起。"),
    "field": ("Softness volume, preferably native .npz.", "软度体数据，推荐原生 .npz。"),
    "charge": ("Charge density; use original SCF density for envelopes/populations.", "电荷密度；包络面和电子数使用原始 SCF 密度。"),
    "demo": ("Open synthetic teaching data.", "打开合成教学数据。"),
    "scene": ("Saved scene JSON, including camera and styling.", "保存的场景 JSON，包含相机和样式。"),
    "example": ("Packaged demo ID from the demos command.", "demos 命令列出的内置示例 ID。"),
    "mode": ("Display mode; otherwise preserve the scene/default.", "显示方式；省略时保留场景或默认设置。"),
    "width": ("Image width in pixels.", "图片宽度，单位像素。"),
    "height": ("Image height in pixels.", "图片高度，单位像素。"),
    "dpi": ("Image DPI metadata.", "图片 DPI 元数据。"),
    "fps": ("Animation frames per second, 1–60.", "动画帧率，1–60 帧/秒。"),
    "seconds": ("Animation duration in seconds, 0.25–120.", "动画总时长，0.25–120 秒。"),
    "turns": ("Number of full rotations, 1–10.", "完整旋转圈数，1–10。"),
    "axis": ("Rotation axis: surface normal, initial view-up, or Cartesian x/y/z.", "旋转轴：表面法线、初始视图上方向，或笛卡尔 x/y/z。"),
    "reverse": ("Reverse the rotation direction.", "反转旋转方向。"),
    "no_fit": ("Keep exact camera framing; default fits the full rotation.", "保持精确构图；默认自动取景以容纳完整旋转。"),
    "labels": ("Integer .npy labels matching field geometry/grid; 0 may mark vacuum.", "与场几何及网格一致的整数 .npy 标签，0 可表示真空。"),
    "reference": ("One reference density, or AECCAR0 AECCAR2 (summed).", "一个参考密度文件，或相加使用的 AECCAR0 AECCAR2。"),
    "executable": ("Bader executable; otherwise use environment/PATH/local install.", "Bader 可执行文件；省略时查找环境变量、PATH 或本地安装。"),
    "vacuum": ("Bader vacuum classification; off assigns the full cell.", "Bader 真空分类；off 将整个晶胞分配给原子。"),
    "surface_atoms": ("One-based IDs whose basin integrals form the surface sum.", "用于表面层求和的原子编号，从 1 开始。"),
    "basins": ("basins.npz generated by the Bader workflow.", "Bader 流程生成的 basins.npz。"),
    "atoms": ("One or more one-based atom IDs.", "一个或多个原子编号，从 1 开始。"),
    "help": ("Show command help and exit.", "显示命令帮助并退出。"),
}


def generate(language):
    zh = language == "zh-CN"
    i = int(zh)
    other = "en" if zh else "zh-CN"
    title = "命令行完整参考" if zh else "Complete CLI reference"
    lines = [f"# Fermi Softness {__version__} — {title}", "",
             f"[{'English' if zh else '中文'}](cli-reference.{other}.md) · "
             f"[{'使用手册' if zh else 'User guide'}](user-guide.{language}.md)", ""]
    lines += [
        "本页由实际命令解析器生成，参数名、必填项、选项和默认值与程序同步。"
        if zh else "Generated from the actual command parser; names, requirements, choices and defaults stay synchronized.",
        "", "```sh", "fermi-softness --version", "fermi-softness --help",
        "fermi-softness compute --help", "```", "",
        "也可用 `python -m fermi_softness` 替代 `fermi-softness`。每个子命令都支持 `-h/--help`。"
        if zh else "You can replace `fermi-softness` with `python -m fermi_softness`. Every subcommand supports `-h/--help`.",
        "",
    ]
    sub = next(a for a in parser()._actions if isinstance(a, argparse._SubParsersAction))
    for name, command in sub.choices.items():
        lines += [f"## `{name}`", "", COMMANDS[name][i], ""]
        lines += ["| 参数 | 必填 | 默认值 / 可选值 | 含义 |" if zh
                  else "| Argument | Required | Default / choices | Meaning |",
                  "|---|---|---|---|"]
        for action in command._actions:
            flags = ", ".join(f"`{f}`" for f in action.option_strings) or f"`{action.dest}`"
            required = action.required or (not action.option_strings and action.nargs not in ("?", "*"))
            req = ("是" if required else "否") if zh else ("yes" if required else "no")
            default = "—" if action.default in (None, argparse.SUPPRESS) else f"`{action.default}`"
            if action.choices:
                default += "; " + ", ".join(f"`{x}`" for x in action.choices)
            description = OPTIONS[action.dest][i]
            lines.append(f"| {flags} | {req} | {default} | {description} |")
        lines.append("")
    if zh:
        lines += ["## 输出目标与运行顺序", "",
                  "`compute`、`compute-parchg` 和 `compute-frozen` 的输出是结果目录；"
                  "`prepare-*` 的输出是供 VASP 运行的目录。准备命令不会自动运行 VASP。", "",
                  "`demo` 输出示例目录；`install-bader` 输出程序安装目录；`bader` 输出分析目录。"
                  "`render` 输出 PNG/TIFF 文件；`integrate` 输出 JSON；`select-basins` 输出 NPZ。", "",
                  "`gui --demo` 打开合成示例；实际材料用 `gui --example pt111` 或 "
                  "`gui --example pt3y111`。不要同时给出互相竞争的数据入口。", "",
                  "外部标签积分不自动寻找 Bader 边界：`integrate` 需要已经对齐的体素标签；"
                  "只给 ACF.dat 不够。需要生成分区时使用 `bader`。", "",
                  "`--allow-incomplete` 与 `--allow-reduced` 生成明确标记的诊断结果，不能用于"
                  "替代足够空带和正确对称性设置。完整实例和错误处理见使用手册。", ""]
    else:
        lines += ["## Output targets and workflow order", "",
                  "`compute`, `compute-parchg` and `compute-frozen` write result directories; "
                  "`prepare-*` write VASP run directories. Preparation does not execute VASP.", "",
                  "`demo` writes a demo directory; `install-bader` an executable directory; `bader` "
                  "an analysis directory. `render` writes PNG/TIFF, `integrate` JSON, and `select-basins` NPZ.", "",
                  "`gui --demo` opens synthetic data. Use `gui --example pt111` or "
                  "`gui --example pt3y111` for material demos. Do not combine competing data inputs.", "",
                  "`integrate` requires already aligned voxel labels, not just ACF.dat, and does not "
                  "find boundaries itself. Use `bader` to generate a charge-defined partition.", "",
                  "`--allow-incomplete` and `--allow-reduced` produce explicitly diagnostic results. "
                  "They do not replace enough empty bands or correct symmetry settings. "
                  "See the user guide for complete examples and error recovery.", ""]
    return "\n".join(lines)


def main():
    args = argparse.ArgumentParser(description=__doc__)
    args.add_argument("--check", action="store_true")
    check = args.parse_args().check
    for language in ("en", "zh-CN"):
        path = ROOT / "docs" / f"cli-reference.{language}.md"
        content = generate(language)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale CLI documentation: {path.name}")
        else:
            path.write_text(content, encoding="utf-8")
    print("CLI documentation is current." if check else "Generated English and Chinese CLI references.")


if __name__ == "__main__":
    main()
